# SERVICE
apiVersion: v1
kind: Service
metadata:
    name: dhrishti-backend-service
spec:
    selector:
        app: django-pod
    ports:
    - port: 80
      name: http
      targetPort: 8000
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dhrishti-backend-deployment
    labels:
        app: django
spec:
    replicas: 1
    selector:
        matchLabels:
            app: django-pod
    template:
        metadata:
            name: dhrishti-backend-pod
            labels:
                app: django-pod
        spec:
            containers:
            - name: dhrishti-backend
              image: eu.gcr.io/arcane-boulder-263622/dhrishti-backend
              env:
                - name: DJANGO_ALLOWED_HOSTS
                  value: dhrishti-backend-service
                - name: DJANGO_DEBUG
                  value: '0'
                - name: PROJECT_ID
                  value: arcane-boulder-263622
                - name: REDDIT_CLIENT_ID
                  value: lGJYd7rcacv-GA
                - name: REDDIT_APPLICATION
                  value: reddit-connector
                - name: DJANGO_SETTINGS_MODULE
                  value: dhrishtisettings.settings
                - name: REDDIT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: dhrishti-secrets
                      key: reddit-secret
                - name: DJANGO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: dhrishti-secrets
                      key: django-secret-key
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: dhrishti-secrets
                      key: google-application-credentials

              ports:
              - containerPort: 8000
